//! Public compatibility fixtures, generated by the pinned runtime's real encoders.
use game_server::*;
use serde_json::{Value, json};
use std::fmt::Write;

fn hex(bytes: &[u8]) -> String {
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(output, "{byte:02x}").unwrap();
    }
    output
}

fn fixtures() -> Value {
    let contract = BROWSER_PROTOCOL_CONTRACT;
    let snapshot = SnapshotFrame {
        tick: 9_007_199_254_740_993,
        state_hash: snapshot_hash(9_007_199_254_740_993, b"{\"version\":1}"),
        payload: b"{\"version\":1}".to_vec(),
    };
    let whole = encode_snapshot(&snapshot).unwrap();
    use scrabble_game::{identity, protocol, ruleset, state};
    let mut game = state::GameState::new(
        identity::GameId::new(1),
        ruleset::english_fixture(),
        [7; 32],
    )
    .unwrap();
    game.add_player(identity::PlayerId::new(1), "Fixture player".into())
        .unwrap();
    game.add_player(identity::PlayerId::new(2), "Other fixture player".into())
        .unwrap();
    game.deal_initial_racks().unwrap();
    let command = protocol::CommandEnvelope {
        version: identity::ProtocolVersion,
        game_id: identity::GameId::new(1),
        player_id: identity::PlayerId::new(1),
        sequence: 4,
        expected_turn: identity::TurnId::new(0),
        command: protocol::Command::Preview {
            placements: vec![protocol::Placement {
                tile_id: identity::TileId::new(1),
                coordinate: identity::Coordinate::new(7, 7).unwrap(),
                blank_as: None,
            }],
        },
    };
    json!({
        "gameCommand": command,
        "playerSnapshot": game.player_snapshot(identity::PlayerId::new(1)).unwrap(),
        "contract": {
            "routeVersion": contract.route_version,
            "gameProtocolVersion": contract.game_protocol_version,
            "controlFormatVersion": contract.control_format_version,
            "reconnectTokenBytes": contract.reconnect_token_bytes,
            "maxCommandPayloadBytes": contract.max_command_payload_bytes,
            "maxCommandRejectionPayloadBytes": contract.max_command_rejection_payload_bytes,
            "maxSnapshotPayloadBytes": contract.max_snapshot_payload_bytes,
            "maxSnapshotFragments": contract.max_snapshot_fragments,
            "maxControlPayloadBytes": contract.max_control_payload_bytes,
            "maxPendingSnapshots": SNAPSHOT_REASSEMBLY_MAX_PENDING,
            "maxBufferedSnapshotBytes": SNAPSHOT_REASSEMBLY_MAX_BUFFERED_BYTES,
            "maxIdleDatagrams": SNAPSHOT_REASSEMBLY_MAX_IDLE_DATAGRAMS,
        },
        "command": hex(&encode_command(4, b"{\"version\":1}").unwrap()),
        "commandRejection": hex(&encode_command_rejection(4, b"{\"kind\":\"invalid_words\",\"words\":[\"TA\"]}").unwrap()),
        "snapshot": hex(&whole),
        "fragments": encode_snapshot_fragments(&whole, 27).unwrap().iter().map(|bytes| hex(bytes)).collect::<Vec<_>>(),
        "welcome": hex(&encode_welcome(Welcome {
            player_id: 42, tick_hz: 20, max_players: 4,
            current_tick: snapshot.tick, connection_epoch: 7,
            reconnect_token: [0xab; RECONNECT_TOKEN_BYTES], reconnect_grace_ticks: 600,
        })),
        "controlRequest": hex(&encode_control_request(b"ping").unwrap()),
        "controlResponse": hex(&encode_control_response(true, b"pong").unwrap()),
        "controlRejected": hex(&encode_control_response(false, b"").unwrap()),
    })
}

fn main() {
    println!("{}", serde_json::to_string_pretty(&fixtures()).unwrap());
}

#[cfg(test)]
mod tests {
    #[test]
    fn committed_browser_wire_fixtures_match_upstream() {
        let committed: serde_json::Value = serde_json::from_str(include_str!(
            "../../../apps/web/src/transport/fixtures/wire.json"
        ))
        .unwrap();
        assert_eq!(committed, super::fixtures());
    }
}
