// Stable semantic keys; gameplay content and private authority are not translated.
export const en = {
  "settings.title": "Settings",
  "settings.language": "Interface language",
  "settings.theme": "Appearance",
  "settings.light": "Light",
  "settings.dark": "Dark",
  "settings.system": "System",
  "settings.storage": "Preferences could not be saved. They apply to this page.",
  "app.player": "Player",
  "app.activePlayer": "the active player",
  "app.preview": "Board preview · Multiplayer is not connected yet.",
  "connection.idle": "Not connected.",
  "connection.connecting": "Connecting…",
  "connection.reconnecting": "Reconnecting… Attempt {attempt} of 3.",
  "connection.restoring": "Restoring game…",
  "connection.connected": "Connected · Player {player}",
  "connection.disconnected": "Disconnected.",
  "connection.closed": "Connection closed.",
  "connection.failed": "Unable to connect. Check your network and retry.",
  "connection.incompatible": "Cannot join: incompatible game protocol.",
  "session.resumeStopped":
    "Reconnect attempts have stopped. Unable to restore this session. It may have expired or been replaced. Retry explicitly to keep your identity.",
  "create.intro": "Create a game to get a join link for your players.",
  "create.creating": "Creating game…",
  "create.action": "Create game",
  "create.retry": "Retry creation",
  "create.failed": "Unable to create a game.",
  "create.invalidInformation": "The server returned invalid join information.",
  "create.invalidSettings": "Invalid game creation settings.",
  "create.missingInformation": "Missing join information.",
  "create.invalidConnection": "Invalid game connection settings.",
  "create.expired": "This creation request has expired. Start a new game request.",
  "create.full": "The server is full. You can retry this request.",
  "create.unavailable": "The server cannot create a game right now. You can retry this request.",
  "create.rejected": "The creation request was rejected.",
  "create.forbidden": "This board is not allowed to create games on the server.",
  "create.retryable": "Unable to create the game. You can retry this request.",
  "create.interrupted": "The response was interrupted. Retry to recover the same game.",
  "join.title": "Join game",
  "join.name": "Player name",
  "join.joining": "Joining game…",
  "join.checking": "Checking game…",
  "join.retry": "Retry join",
  "join.invalidInvite":
    "This invitation has an invalid game identifier. Ask the host for a new link.",
  "join.unconfigured": "The game service is not configured. Ask the host for a new invitation.",
  "join.invalidId": "This game identifier is invalid. Ask the host for a new invitation.",
  "join.full": "This game is full. Ask the host for another invitation.",
  "join.started": "This game has already started. New players cannot join.",
  "join.expired": "This game has expired. Ask the host for a new invitation.",
  "join.unavailable": "This game is no longer available. Ask the host for a new invitation.",
  "join.checkFailed": "Unable to check this game. Check your connection and retry.",
  "join.differentGame": "The server returned a different game.",
  "phone.savedUnreadable":
    "The saved player session cannot be read. You can explicitly join as a new player.",
  "phone.saveFailed": "Unable to save this player session. Allow tab storage and reconnect.",
  "phone.ended": "The player connection ended. Reconnect to keep your identity.",
  "phone.lateSeat":
    "The game started before your player seat was admitted. Ask the host for another invitation.",
  "phone.chooseName": "Choose a name to finish joining.",
  "phone.lateName": "The game started before your name was saved. You are joined as {name}.",
  "phone.nameUnconfirmed":
    "Your name was not confirmed. Reconnect to retry with the same identity.",
  "phone.nameSendFailed": "Unable to send your name. Reconnect to retry.",
  "phone.resumeFailed":
    "This player session could not reconnect. Retry, or explicitly join as a new player.",
  "phone.connectFailed":
    "Unable to establish the player connection. Check your browser and network, then retry.",
  "phone.invalidName": "Choose a name of 1 to 32 characters without control characters.",
  "phone.clearFailed": "Unable to clear the saved session. Allow tab storage and retry.",
  "phone.retry": "Retry player connection",
  "phone.new": "Join as a new player",
  "phone.identity": "Player {player}",
  "phone.waitHost": "Waiting for the host to start.",
  "phone.yourTurn": "It is your turn.",
  "phone.waitPlayer": "Waiting for {name}.",
  "phone.finished": "Game finished.",
  "invite.failed": "Unable to create a player invitation for this game.",
  "invite.title": "Player invitation",
  "invite.scan": "Scan to join this game",
  "invite.link": "Join this game",
  "invite.copy": "Copy player link",
  "invite.copied": "Player link copied.",
  "invite.copyFailed": "Unable to copy. Open the join link and copy its address.",
  "board.title": "Scrabble board",
  "board.dimensions": "{rows} rows and {columns} columns",
  "board.coordinates": "Coordinates",
  "board.waiting": "Waiting for game",
  "board.turn": "{name}'s turn",
  "board.winner": "Winner: {names}",
  "board.tie": "Tie: {names}",
  "board.noWinner": "No winner",
  "board.status": "Game status",
  "board.turnNumber": "Turn {turn}",
  "board.tentative": "Dashed tiles are tentative.",
  "board.finished": "Game finished",
  "board.players": "Players and scores",
  "board.connected": "Connected",
  "board.disconnected": "Disconnected",
  "board.active": " (active)",
  "board.waitPlayers": "Waiting for players to join.",
  "board.remaining": "{count} tiles remaining",
  "board.square": "Row {row}, column {column}: {description}",
  "board.committed": "Committed {letter}, {points} points",
  "board.committedBlank": "Committed {letter}, {points} points, blank",
  "board.preview": "Tentative {letter}, {points} points",
  "board.previewBlank": "Tentative {letter}, {points} points, blank",
  "score.points": "{count} points",
  "score.unknown": "unknown",
  "premiumShort.normal": "",
  "premiumShort.double_letter": "DL",
  "premiumShort.triple_letter": "TL",
  "premiumShort.double_word": "DW",
  "premiumShort.triple_word": "TW",
  "premium.normal": "Normal square",
  "premium.double_letter": "Double letter",
  "premium.triple_letter": "Triple letter",
  "premium.double_word": "Double word",
  "premium.triple_word": "Triple word",
  "rack.title": "Your tiles",
  "rack.list": "Your rack",
  "rack.blank": "Blank tile, {points} points",
  "rack.letter": "{letter}, {points} points",
  "rack.placed": "{description}, placed in draft",
  "rack.empty": "Your rack is empty.",
  "board.recoverFailed":
    "Unable to recover this board session. Use the original board tab or create a new game.",
  "board.connectFailed": "Unable to start the connection.",
  "board.reconnect": "Reconnect",
  "lobby.title": "Lobby controls",
  "lobby.start": "Start game",
  "lobby.starting": "Starting…",
  "lobby.minimum": "At least {count} players are needed.",
  "lobby.claimTimeout": "Board ownership was not confirmed. Reconnect and retry.",
  "lobby.claimFailed": "Unable to confirm board ownership. Reconnect and retry.",
  "lobby.startTimeout": "Start was not confirmed. You can retry.",
  "lobby.startFailed": "Unable to send Start. Reconnect and retry.",
  "editor.title": "Move editor",
  "editor.board": "Placement board",
  "editor.chooseSquare": "Choose a square",
  "command.help": "Keyboard controls",
  "command.left": "Move left",
  "command.right": "Move right",
  "command.up": "Move up",
  "command.down": "Move down",
  "command.first": "First square in row",
  "command.last": "Last square in row",
  "command.place": "Select a tile or place it on the focused square",
  "command.cancel": "Cancel selection or confirmation",
  "editor.keyboard":
    "Arrow keys choose a square. Enter or Space places the selected tile. Escape cancels selection.",
  "editor.blankTitle": "Choose blank letter",
  "editor.cancelBlank": "Cancel blank choice",
  "editor.return": "Return selected tile",
  "editor.cancel": "Cancel move",
  "editor.commit": "Commit move",
  "editor.pass": "Pass turn",
  "editor.exchange": "Exchange tiles",
  "editor.confirmPass": "Confirm pass",
  "editor.confirmExchange": "Confirm exchange",
  "editor.keep": "Keep playing",
  "editor.exchangeMinimum": "Exchange requires at least {count} tiles in the bag.",
  "editor.exchangeHelp":
    "Choose tiles in your rack. Exchanging ends your turn and clears your draft.",
  "editor.passHelp": "Pass this turn? Your draft will be cleared.",
  "editor.connectionChanged":
    "Connection changed. Check the restored turn before submitting again.",
  "editor.invalidWords": "Not in the dictionary: {words}. Your draft is kept.",
  "editor.cleared": "The game changed. Your draft was cleared.",
  "editor.ready": "Ready to commit. Word acceptance is checked by the server.",
  "editor.reconnect": "Reconnect to edit. Your draft is kept.",
  "editor.exchangeSelected": "Select rack tiles to exchange. {count} selected.",
  "editor.cancelled": "Selection cancelled. Select a tile again.",
  "editor.squareEmpty": "Row {row}, column {column}: empty",
  "editor.squareCenter": "Row {row}, column {column}: center",
  "editor.squareDraft": "Row {row}, column {column}: tentative {letter}",
  "editor.squareFixed": "Row {row}, column {column}: committed {letter}",
  "history.title": "Turn history",
  "history.latest": "Showing the latest {count} turns.",
  "history.turn": "Turn {turn}: {name}",
  "history.move": "{words} · {points} points",
  "history.moveBlank": "{words} · {points} points · {blanks} blank",
  "history.moveBlanks": "{words} · {points} points · {blanks} blanks",
  "history.pass": "Passed",
  "history.exchangeOne": "Exchanged {count} tile",
  "history.exchangeOther": "Exchanged {count} tiles",
  "history.score": "{name} {delta} ({score})",
  "draft.changed": "The game changed. Start a fresh draft.",
  "draft.waiting": "Wait for your turn.",
  "draft.empty": "Select a tile and a board square.",
  "draft.too-many": "Use no more tiles than your rack holds.",
  "draft.not-owned": "This tile is no longer in your rack.",
  "draft.duplicate": "Use each tile and square only once.",
  "draft.coordinate": "Choose a square inside the board.",
  "draft.occupied": "That square already has a committed tile.",
  "draft.blank": "Choose a valid letter for the blank.",
  "draft.not-line": "Place all new tiles in one row or column.",
  "draft.gap": "Fill the gaps between your tiles.",
  "draft.center": "The first move must cover the center square.",
  "draft.no-word": "A move must form a word of at least two letters.",
  "draft.disconnected": "Connect your move to a committed tile.",
  "editor.moveTimeout": "Move was not confirmed. Your draft is kept; you can retry.",
  "editor.moveFailed": "Unable to send the move. Your draft is kept.",
  "editor.movePending": "Waiting for move confirmation…",
  "editor.passTimeout": "Pass was not confirmed. Your draft is kept; you can retry.",
  "editor.passFailed": "Unable to send the pass. Your draft is kept.",
  "editor.passPending": "Waiting for pass confirmation…",
  "editor.exchangeTimeout": "Exchange was not confirmed. Your draft is kept; you can retry.",
  "editor.exchangeFailed": "Unable to send the exchange. Your draft is kept.",
  "editor.exchangePending": "Waiting for exchange confirmation…",
} as const;
export type CopyKey = keyof typeof en;
const de: Record<CopyKey, string> = {
  "settings.title": "Einstellungen",
  "settings.language": "Sprache der Oberfläche",
  "settings.theme": "Darstellung",
  "settings.light": "Hell",
  "settings.dark": "Dunkel",
  "settings.system": "System",
  "settings.storage":
    "Die Einstellungen konnten nicht gespeichert werden. Sie gelten für diese Seite.",
  "app.player": "Spieler",
  "app.activePlayer": "den aktiven Spieler",
  "app.preview": "Spielbrettvorschau · Mehrspieler ist noch nicht verbunden.",
  "connection.idle": "Nicht verbunden.",
  "connection.connecting": "Verbindung wird hergestellt…",
  "connection.reconnecting": "Verbindung wird wiederhergestellt… Versuch {attempt} von 3.",
  "connection.restoring": "Spiel wird wiederhergestellt…",
  "connection.connected": "Verbunden · Spieler {player}",
  "connection.disconnected": "Verbindung getrennt.",
  "connection.closed": "Verbindung beendet.",
  "connection.failed": "Verbindung nicht möglich. Prüfe dein Netzwerk und versuche es erneut.",
  "connection.incompatible": "Beitritt nicht möglich: inkompatibles Spielprotokoll.",
  "session.resumeStopped":
    "Die Verbindungsversuche wurden beendet. Diese Sitzung konnte nicht wiederhergestellt werden. Sie ist möglicherweise abgelaufen oder ersetzt worden. Versuche es ausdrücklich erneut, um deine Identität zu behalten.",
  "create.intro": "Erstelle ein Spiel, um einen Beitrittslink für deine Mitspieler zu erhalten.",
  "create.creating": "Spiel wird erstellt…",
  "create.action": "Spiel erstellen",
  "create.retry": "Erneut erstellen",
  "create.failed": "Spiel konnte nicht erstellt werden.",
  "create.invalidInformation": "Der Server hat ungültige Beitrittsinformationen geliefert.",
  "create.invalidSettings": "Ungültige Einstellungen für die Spielerstellung.",
  "create.missingInformation": "Beitrittsinformationen fehlen.",
  "create.invalidConnection": "Ungültige Verbindungseinstellungen für das Spiel.",
  "create.expired": "Diese Anfrage ist abgelaufen. Starte eine neue Spielerstellung.",
  "create.full": "Der Server ist voll. Du kannst die Anfrage erneut versuchen.",
  "create.unavailable":
    "Der Server kann gerade kein Spiel erstellen. Du kannst die Anfrage erneut versuchen.",
  "create.rejected": "Die Spielerstellung wurde abgelehnt.",
  "create.forbidden": "Dieses Spielbrett darf auf dem Server keine Spiele erstellen.",
  "create.retryable": "Spiel konnte nicht erstellt werden. Du kannst die Anfrage erneut versuchen.",
  "create.interrupted":
    "Die Antwort wurde unterbrochen. Versuche es erneut, um dasselbe Spiel wiederherzustellen.",
  "join.title": "Spiel beitreten",
  "join.name": "Spielername",
  "join.joining": "Spielbeitritt läuft…",
  "join.checking": "Spiel wird geprüft…",
  "join.retry": "Beitritt erneut versuchen",
  "join.invalidInvite":
    "Diese Einladung enthält eine ungültige Spielkennung. Bitte den Gastgeber um einen neuen Link.",
  "join.unconfigured":
    "Der Spieldienst ist nicht eingerichtet. Bitte den Gastgeber um eine neue Einladung.",
  "join.invalidId": "Diese Spielkennung ist ungültig. Bitte den Gastgeber um eine neue Einladung.",
  "join.full": "Dieses Spiel ist voll. Bitte den Gastgeber um eine andere Einladung.",
  "join.started": "Dieses Spiel hat bereits begonnen. Neue Spieler können nicht mehr beitreten.",
  "join.expired": "Dieses Spiel ist abgelaufen. Bitte den Gastgeber um eine neue Einladung.",
  "join.unavailable":
    "Dieses Spiel ist nicht mehr verfügbar. Bitte den Gastgeber um eine neue Einladung.",
  "join.checkFailed":
    "Dieses Spiel konnte nicht geprüft werden. Prüfe deine Verbindung und versuche es erneut.",
  "join.differentGame": "Der Server hat ein anderes Spiel geliefert.",
  "phone.savedUnreadable":
    "Die gespeicherte Sitzung kann nicht gelesen werden. Du kannst ausdrücklich als neuer Spieler beitreten.",
  "phone.saveFailed":
    "Die Sitzung konnte nicht gespeichert werden. Erlaube Tab-Speicher und verbinde dich erneut.",
  "phone.ended":
    "Die Spielerverbindung wurde beendet. Verbinde dich erneut, um deine Identität zu behalten.",
  "phone.lateSeat":
    "Das Spiel begann vor deinem Beitritt. Bitte den Gastgeber um eine andere Einladung.",
  "phone.chooseName": "Wähle einen Namen, um den Beitritt abzuschließen.",
  "phone.lateName": "Das Spiel begann, bevor dein Name gespeichert wurde. Du spielst als {name}.",
  "phone.nameUnconfirmed":
    "Dein Name wurde nicht bestätigt. Verbinde dich erneut, um es mit derselben Identität zu versuchen.",
  "phone.nameSendFailed":
    "Dein Name konnte nicht gesendet werden. Verbinde dich erneut und versuche es noch einmal.",
  "phone.resumeFailed":
    "Diese Sitzung konnte nicht wiederhergestellt werden. Versuche es erneut oder tritt ausdrücklich als neuer Spieler bei.",
  "phone.connectFailed":
    "Die Spielerverbindung konnte nicht hergestellt werden. Prüfe Browser und Netzwerk und versuche es erneut.",
  "phone.invalidName": "Wähle einen Namen mit 1 bis 32 Zeichen ohne Steuerzeichen.",
  "phone.clearFailed":
    "Die gespeicherte Sitzung konnte nicht gelöscht werden. Erlaube Tab-Speicher und versuche es erneut.",
  "phone.retry": "Spielerverbindung erneut versuchen",
  "phone.new": "Als neuer Spieler beitreten",
  "phone.identity": "Spieler {player}",
  "phone.waitHost": "Warten auf den Spielstart durch den Gastgeber.",
  "phone.yourTurn": "Du bist am Zug.",
  "phone.waitPlayer": "Warten auf {name}.",
  "phone.finished": "Spiel beendet.",
  "invite.failed": "Für dieses Spiel konnte keine Einladung erstellt werden.",
  "invite.title": "Spielereinladung",
  "invite.scan": "Scannen, um diesem Spiel beizutreten",
  "invite.link": "Diesem Spiel beitreten",
  "invite.copy": "Spielerlink kopieren",
  "invite.copied": "Spielerlink kopiert.",
  "invite.copyFailed": "Kopieren nicht möglich. Öffne den Beitrittslink und kopiere die Adresse.",
  "board.title": "Scrabble-Spielbrett",
  "board.dimensions": "{rows} Zeilen und {columns} Spalten",
  "board.coordinates": "Koordinaten",
  "board.waiting": "Warten auf ein Spiel",
  "board.turn": "{name} ist am Zug",
  "board.winner": "Gewinner: {names}",
  "board.tie": "Gleichstand: {names}",
  "board.noWinner": "Kein Gewinner",
  "board.status": "Spielstatus",
  "board.turnNumber": "Zug {turn}",
  "board.tentative": "Gestrichelte Steine sind vorläufig.",
  "board.finished": "Spiel beendet",
  "board.players": "Spieler und Punkte",
  "board.connected": "Verbunden",
  "board.disconnected": "Getrennt",
  "board.active": " (am Zug)",
  "board.waitPlayers": "Warten auf weitere Spieler.",
  "board.remaining": "{count} Steine verbleiben",
  "board.square": "Zeile {row}, Spalte {column}: {description}",
  "board.committed": "Gelegt: {letter}, {points} Punkte",
  "board.committedBlank": "Gelegt: {letter}, {points} Punkte, Blanko",
  "board.preview": "Vorläufig: {letter}, {points} Punkte",
  "board.previewBlank": "Vorläufig: {letter}, {points} Punkte, Blanko",
  "score.points": "{count} Punkte",
  "score.unknown": "unbekannt",
  "premiumShort.normal": "",
  "premiumShort.double_letter": "2B",
  "premiumShort.triple_letter": "3B",
  "premiumShort.double_word": "2W",
  "premiumShort.triple_word": "3W",
  "premium.normal": "Normales Feld",
  "premium.double_letter": "Doppelter Buchstabenwert",
  "premium.triple_letter": "Dreifacher Buchstabenwert",
  "premium.double_word": "Doppelter Wortwert",
  "premium.triple_word": "Dreifacher Wortwert",
  "rack.title": "Deine Steine",
  "rack.list": "Deine Ablage",
  "rack.blank": "Blankostein, {points} Punkte",
  "rack.letter": "{letter}, {points} Punkte",
  "rack.placed": "{description}, im Entwurf gelegt",
  "rack.empty": "Deine Ablage ist leer.",
  "board.recoverFailed":
    "Diese Spielbrettsitzung kann nicht wiederhergestellt werden. Verwende den ursprünglichen Tab oder erstelle ein neues Spiel.",
  "board.connectFailed": "Die Verbindung konnte nicht gestartet werden.",
  "board.reconnect": "Erneut verbinden",
  "lobby.title": "Warteraum-Steuerung",
  "lobby.start": "Spiel starten",
  "lobby.starting": "Spiel startet…",
  "lobby.minimum": "Mindestens {count} Spieler werden benötigt.",
  "lobby.claimTimeout":
    "Die Spielbrett-Zuständigkeit wurde nicht bestätigt. Verbinde dich erneut und versuche es noch einmal.",
  "lobby.claimFailed":
    "Die Spielbrett-Zuständigkeit konnte nicht bestätigt werden. Verbinde dich erneut und versuche es noch einmal.",
  "lobby.startTimeout": "Der Start wurde nicht bestätigt. Du kannst es erneut versuchen.",
  "lobby.startFailed":
    "Der Start konnte nicht gesendet werden. Verbinde dich erneut und versuche es noch einmal.",
  "editor.title": "Zugeditor",
  "editor.board": "Brett zum Legen",
  "editor.chooseSquare": "Feld wählen",
  "command.help": "Tastatursteuerung",
  "command.left": "Nach links",
  "command.right": "Nach rechts",
  "command.up": "Nach oben",
  "command.down": "Nach unten",
  "command.first": "Erstes Feld der Zeile",
  "command.last": "Letztes Feld der Zeile",
  "command.place": "Stein wählen oder auf das fokussierte Feld legen",
  "command.cancel": "Auswahl oder Bestätigung abbrechen",
  "editor.keyboard":
    "Pfeiltasten wählen ein Feld. Eingabe oder Leertaste legt den ausgewählten Stein. Escape beendet die Auswahl.",
  "editor.blankTitle": "Buchstaben für Blanko wählen",
  "editor.cancelBlank": "Blanko-Auswahl abbrechen",
  "editor.return": "Ausgewählten Stein zurücklegen",
  "editor.cancel": "Zug abbrechen",
  "editor.commit": "Zug bestätigen",
  "editor.pass": "Passen",
  "editor.exchange": "Steine tauschen",
  "editor.confirmPass": "Passen bestätigen",
  "editor.confirmExchange": "Tausch bestätigen",
  "editor.keep": "Weiterspielen",
  "editor.exchangeMinimum": "Zum Tauschen müssen mindestens {count} Steine im Beutel sein.",
  "editor.exchangeHelp":
    "Wähle Steine aus deiner Ablage. Der Tausch beendet deinen Zug und löscht den Entwurf.",
  "editor.passHelp": "Diesen Zug passen? Dein Entwurf wird gelöscht.",
  "editor.connectionChanged":
    "Die Verbindung hat sich geändert. Prüfe den wiederhergestellten Zug vor dem erneuten Senden.",
  "editor.invalidWords": "Nicht im Wörterbuch: {words}. Dein Entwurf bleibt erhalten.",
  "editor.cleared": "Das Spiel hat sich geändert. Dein Entwurf wurde gelöscht.",
  "editor.ready": "Bereit zum Bestätigen. Der Server prüft die Wörter.",
  "editor.reconnect": "Verbinde dich erneut, um zu bearbeiten. Dein Entwurf bleibt erhalten.",
  "editor.exchangeSelected": "Wähle Steine zum Tauschen. {count} ausgewählt.",
  "editor.cancelled": "Auswahl abgebrochen. Wähle erneut einen Stein.",
  "editor.squareEmpty": "Zeile {row}, Spalte {column}: leer",
  "editor.squareCenter": "Zeile {row}, Spalte {column}: Mitte",
  "editor.squareDraft": "Zeile {row}, Spalte {column}: vorläufig {letter}",
  "editor.squareFixed": "Zeile {row}, Spalte {column}: gelegt {letter}",
  "history.title": "Zugverlauf",
  "history.latest": "Die letzten {count} Züge werden angezeigt.",
  "history.turn": "Zug {turn}: {name}",
  "history.move": "{words} · {points} Punkte",
  "history.moveBlank": "{words} · {points} Punkte · {blanks} Blanko",
  "history.moveBlanks": "{words} · {points} Punkte · {blanks} Blankos",
  "history.pass": "Gepasst",
  "history.exchangeOne": "{count} Stein getauscht",
  "history.exchangeOther": "{count} Steine getauscht",
  "history.score": "{name} {delta} ({score})",
  "draft.changed": "Das Spiel hat sich geändert. Beginne einen neuen Entwurf.",
  "draft.waiting": "Warte, bis du am Zug bist.",
  "draft.empty": "Wähle einen Stein und ein Feld.",
  "draft.too-many": "Verwende höchstens die Steine deiner Ablage.",
  "draft.not-owned": "Dieser Stein ist nicht mehr in deiner Ablage.",
  "draft.duplicate": "Verwende jeden Stein und jedes Feld nur einmal.",
  "draft.coordinate": "Wähle ein Feld innerhalb des Bretts.",
  "draft.occupied": "Auf diesem Feld liegt bereits ein Stein.",
  "draft.blank": "Wähle einen gültigen Buchstaben für den Blanko.",
  "draft.not-line": "Lege alle neuen Steine in eine Zeile oder Spalte.",
  "draft.gap": "Fülle die Lücken zwischen deinen Steinen.",
  "draft.center": "Der erste Zug muss das mittlere Feld belegen.",
  "draft.no-word": "Ein Zug muss ein Wort mit mindestens zwei Buchstaben bilden.",
  "draft.disconnected": "Verbinde deinen Zug mit einem bereits gelegten Stein.",
  "editor.moveTimeout":
    "Zug wurde nicht bestätigt. Dein Entwurf bleibt erhalten; du kannst es erneut versuchen.",
  "editor.moveFailed": "Zug konnte nicht gesendet werden. Dein Entwurf bleibt erhalten.",
  "editor.movePending": "Warten auf Bestätigung: Zug…",
  "editor.passTimeout":
    "Passen wurde nicht bestätigt. Dein Entwurf bleibt erhalten; du kannst es erneut versuchen.",
  "editor.passFailed": "Passen konnte nicht gesendet werden. Dein Entwurf bleibt erhalten.",
  "editor.passPending": "Warten auf Bestätigung: Passen…",
  "editor.exchangeTimeout":
    "Tausch wurde nicht bestätigt. Dein Entwurf bleibt erhalten; du kannst es erneut versuchen.",
  "editor.exchangeFailed": "Tausch konnte nicht gesendet werden. Dein Entwurf bleibt erhalten.",
  "editor.exchangePending": "Warten auf Bestätigung: Tausch…",
};
const es: Record<CopyKey, string> = {
  "settings.title": "Ajustes",
  "settings.language": "Idioma de la interfaz",
  "settings.theme": "Apariencia",
  "settings.light": "Claro",
  "settings.dark": "Oscuro",
  "settings.system": "Sistema",
  "settings.storage": "No se pudieron guardar los ajustes. Se aplican a esta página.",
  "app.player": "Jugador",
  "app.activePlayer": "el jugador activo",
  "app.preview": "Vista previa del tablero · El multijugador aún no está conectado.",
  "connection.idle": "Sin conexión.",
  "connection.connecting": "Conectando…",
  "connection.reconnecting": "Reconectando… Intento {attempt} de 3.",
  "connection.restoring": "Restaurando la partida…",
  "connection.connected": "Conectado · Jugador {player}",
  "connection.disconnected": "Desconectado.",
  "connection.closed": "Conexión cerrada.",
  "connection.failed": "No se pudo conectar. Comprueba la red e inténtalo de nuevo.",
  "connection.incompatible": "No se puede entrar: protocolo de juego incompatible.",
  "session.resumeStopped":
    "Los intentos de reconexión se han detenido. No se pudo restaurar esta sesión. Puede haber caducado o sido reemplazada. Reinténtalo para conservar tu identidad.",
  "create.intro": "Crea una partida para obtener un enlace para tus jugadores.",
  "create.creating": "Creando la partida…",
  "create.action": "Crear partida",
  "create.retry": "Reintentar creación",
  "create.failed": "No se pudo crear una partida.",
  "create.invalidInformation": "El servidor devolvió información de acceso no válida.",
  "create.invalidSettings": "Ajustes de creación de partidas no válidos.",
  "create.missingInformation": "Falta la información de acceso.",
  "create.invalidConnection": "Ajustes de conexión de la partida no válidos.",
  "create.expired": "Esta solicitud ha caducado. Inicia una nueva solicitud de partida.",
  "create.full": "El servidor está lleno. Puedes reintentar esta solicitud.",
  "create.unavailable":
    "El servidor no puede crear una partida ahora. Puedes reintentar esta solicitud.",
  "create.rejected": "Se rechazó la solicitud de creación.",
  "create.forbidden": "Este tablero no tiene permiso para crear partidas en el servidor.",
  "create.retryable": "No se pudo crear la partida. Puedes reintentar esta solicitud.",
  "create.interrupted": "La respuesta se interrumpió. Reinténtalo para recuperar la misma partida.",
  "join.title": "Entrar en la partida",
  "join.name": "Nombre del jugador",
  "join.joining": "Entrando en la partida…",
  "join.checking": "Comprobando la partida…",
  "join.retry": "Reintentar acceso",
  "join.invalidInvite":
    "Esta invitación tiene un identificador de partida no válido. Pide al anfitrión un enlace nuevo.",
  "join.unconfigured":
    "El servicio de juego no está configurado. Pide al anfitrión una invitación nueva.",
  "join.invalidId":
    "Este identificador de partida no es válido. Pide al anfitrión una invitación nueva.",
  "join.full": "Esta partida está llena. Pide al anfitrión otra invitación.",
  "join.started": "Esta partida ya ha comenzado. No pueden entrar jugadores nuevos.",
  "join.expired": "Esta partida ha caducado. Pide al anfitrión una invitación nueva.",
  "join.unavailable": "Esta partida ya no está disponible. Pide al anfitrión una invitación nueva.",
  "join.checkFailed":
    "No se pudo comprobar la partida. Comprueba tu conexión e inténtalo de nuevo.",
  "join.differentGame": "El servidor devolvió otra partida.",
  "phone.savedUnreadable": "No se puede leer la sesión guardada. Puedes entrar como jugador nuevo.",
  "phone.saveFailed":
    "No se pudo guardar la sesión. Permite el almacenamiento de la pestaña y vuelve a conectar.",
  "phone.ended": "La conexión del jugador terminó. Vuelve a conectar para conservar tu identidad.",
  "phone.lateSeat":
    "La partida comenzó antes de admitir tu plaza. Pide al anfitrión otra invitación.",
  "phone.chooseName": "Elige un nombre para terminar de entrar.",
  "phone.lateName": "La partida comenzó antes de guardar tu nombre. Has entrado como {name}.",
  "phone.nameUnconfirmed":
    "Tu nombre no se confirmó. Vuelve a conectar para reintentarlo con la misma identidad.",
  "phone.nameSendFailed": "No se pudo enviar tu nombre. Vuelve a conectar para reintentarlo.",
  "phone.resumeFailed": "Esta sesión no pudo reconectarse. Reinténtalo o entra como jugador nuevo.",
  "phone.connectFailed":
    "No se pudo conectar al jugador. Comprueba el navegador y la red e inténtalo de nuevo.",
  "phone.invalidName": "Elige un nombre de 1 a 32 caracteres sin caracteres de control.",
  "phone.clearFailed":
    "No se pudo borrar la sesión guardada. Permite el almacenamiento de la pestaña y reinténtalo.",
  "phone.retry": "Reintentar conexión del jugador",
  "phone.new": "Entrar como jugador nuevo",
  "phone.identity": "Jugador {player}",
  "phone.waitHost": "Esperando a que el anfitrión empiece.",
  "phone.yourTurn": "Es tu turno.",
  "phone.waitPlayer": "Esperando a {name}.",
  "phone.finished": "Partida terminada.",
  "invite.failed": "No se pudo crear una invitación para esta partida.",
  "invite.title": "Invitación de jugadores",
  "invite.scan": "Escanea para entrar en esta partida",
  "invite.link": "Entrar en esta partida",
  "invite.copy": "Copiar enlace de jugador",
  "invite.copied": "Enlace de jugador copiado.",
  "invite.copyFailed": "No se pudo copiar. Abre el enlace de acceso y copia su dirección.",
  "board.title": "Tablero de Scrabble",
  "board.dimensions": "{rows} filas y {columns} columnas",
  "board.coordinates": "Coordenadas",
  "board.waiting": "Esperando una partida",
  "board.turn": "Turno de {name}",
  "board.winner": "Ganador: {names}",
  "board.tie": "Empate: {names}",
  "board.noWinner": "Sin ganador",
  "board.status": "Estado de la partida",
  "board.turnNumber": "Turno {turn}",
  "board.tentative": "Las fichas con borde discontinuo son provisionales.",
  "board.finished": "Partida terminada",
  "board.players": "Jugadores y puntuaciones",
  "board.connected": "Conectado",
  "board.disconnected": "Desconectado",
  "board.active": " (activo)",
  "board.waitPlayers": "Esperando a que entren jugadores.",
  "board.remaining": "Quedan {count} fichas",
  "board.square": "Fila {row}, columna {column}: {description}",
  "board.committed": "Colocada: {letter}, {points} puntos",
  "board.committedBlank": "Colocada: {letter}, {points} puntos, comodín",
  "board.preview": "Provisional: {letter}, {points} puntos",
  "board.previewBlank": "Provisional: {letter}, {points} puntos, comodín",
  "score.points": "{count} puntos",
  "score.unknown": "desconocido",
  "premiumShort.normal": "",
  "premiumShort.double_letter": "DL",
  "premiumShort.triple_letter": "TL",
  "premiumShort.double_word": "DP",
  "premiumShort.triple_word": "TP",
  "premium.normal": "Casilla normal",
  "premium.double_letter": "Doble letra",
  "premium.triple_letter": "Triple letra",
  "premium.double_word": "Doble palabra",
  "premium.triple_word": "Triple palabra",
  "rack.title": "Tus fichas",
  "rack.list": "Tu atril",
  "rack.blank": "Comodín, {points} puntos",
  "rack.letter": "{letter}, {points} puntos",
  "rack.placed": "{description}, colocada en el borrador",
  "rack.empty": "Tu atril está vacío.",
  "board.recoverFailed":
    "No se pudo recuperar esta sesión del tablero. Usa la pestaña original o crea una partida nueva.",
  "board.connectFailed": "No se pudo iniciar la conexión.",
  "board.reconnect": "Reconectar",
  "lobby.title": "Controles de la sala",
  "lobby.start": "Empezar partida",
  "lobby.starting": "Empezando…",
  "lobby.minimum": "Se necesitan al menos {count} jugadores.",
  "lobby.claimTimeout": "No se confirmó el control del tablero. Vuelve a conectar y reinténtalo.",
  "lobby.claimFailed":
    "No se pudo confirmar el control del tablero. Vuelve a conectar y reinténtalo.",
  "lobby.startTimeout": "El inicio no se confirmó. Puedes reintentarlo.",
  "lobby.startFailed": "No se pudo enviar el inicio. Vuelve a conectar y reinténtalo.",
  "editor.title": "Editor de jugadas",
  "editor.board": "Tablero de colocación",
  "editor.chooseSquare": "Elige una casilla",
  "command.help": "Controles del teclado",
  "command.left": "Mover a la izquierda",
  "command.right": "Mover a la derecha",
  "command.up": "Mover arriba",
  "command.down": "Mover abajo",
  "command.first": "Primera casilla de la fila",
  "command.last": "Última casilla de la fila",
  "command.place": "Elegir una ficha o colocarla en la casilla enfocada",
  "command.cancel": "Cancelar selección o confirmación",
  "editor.keyboard":
    "Las flechas eligen una casilla. Intro o Espacio coloca la ficha seleccionada. Escape cancela la selección.",
  "editor.blankTitle": "Elige la letra del comodín",
  "editor.cancelBlank": "Cancelar elección del comodín",
  "editor.return": "Devolver ficha seleccionada",
  "editor.cancel": "Cancelar jugada",
  "editor.commit": "Confirmar jugada",
  "editor.pass": "Pasar turno",
  "editor.exchange": "Cambiar fichas",
  "editor.confirmPass": "Confirmar pase",
  "editor.confirmExchange": "Confirmar cambio",
  "editor.keep": "Seguir jugando",
  "editor.exchangeMinimum": "Para cambiar se necesitan al menos {count} fichas en la bolsa.",
  "editor.exchangeHelp": "Elige fichas de tu atril. Cambiar termina tu turno y borra el borrador.",
  "editor.passHelp": "¿Pasar este turno? Se borrará tu borrador.",
  "editor.connectionChanged":
    "La conexión cambió. Comprueba el turno restaurado antes de enviarlo de nuevo.",
  "editor.invalidWords": "No está en el diccionario: {words}. Se conserva tu borrador.",
  "editor.cleared": "La partida cambió. Se borró tu borrador.",
  "editor.ready": "Listo para confirmar. El servidor comprueba las palabras.",
  "editor.reconnect": "Vuelve a conectar para editar. Se conserva tu borrador.",
  "editor.exchangeSelected": "Selecciona fichas para cambiar. {count} seleccionadas.",
  "editor.cancelled": "Selección cancelada. Selecciona otra ficha.",
  "editor.squareEmpty": "Fila {row}, columna {column}: vacía",
  "editor.squareCenter": "Fila {row}, columna {column}: centro",
  "editor.squareDraft": "Fila {row}, columna {column}: provisional {letter}",
  "editor.squareFixed": "Fila {row}, columna {column}: colocada {letter}",
  "history.title": "Historial de turnos",
  "history.latest": "Se muestran los últimos {count} turnos.",
  "history.turn": "Turno {turn}: {name}",
  "history.move": "{words} · {points} puntos",
  "history.moveBlank": "{words} · {points} puntos · {blanks} comodín",
  "history.moveBlanks": "{words} · {points} puntos · {blanks} comodines",
  "history.pass": "Pasó",
  "history.exchangeOne": "Cambió {count} ficha",
  "history.exchangeOther": "Cambió {count} fichas",
  "history.score": "{name} {delta} ({score})",
  "draft.changed": "La partida cambió. Empieza un borrador nuevo.",
  "draft.waiting": "Espera tu turno.",
  "draft.empty": "Selecciona una ficha y una casilla.",
  "draft.too-many": "No uses más fichas de las que tiene tu atril.",
  "draft.not-owned": "Esta ficha ya no está en tu atril.",
  "draft.duplicate": "Usa cada ficha y casilla solo una vez.",
  "draft.coordinate": "Elige una casilla dentro del tablero.",
  "draft.occupied": "Esa casilla ya tiene una ficha colocada.",
  "draft.blank": "Elige una letra válida para el comodín.",
  "draft.not-line": "Coloca todas las fichas nuevas en una fila o columna.",
  "draft.gap": "Rellena los huecos entre tus fichas.",
  "draft.center": "La primera jugada debe cubrir la casilla central.",
  "draft.no-word": "Una jugada debe formar una palabra de al menos dos letras.",
  "draft.disconnected": "Conecta tu jugada con una ficha ya colocada.",
  "editor.moveTimeout": "No se confirmó: Jugada. Se conserva tu borrador; puedes reintentarlo.",
  "editor.moveFailed": "No se pudo enviar: Jugada. Se conserva tu borrador.",
  "editor.movePending": "Esperando confirmación: Jugada…",
  "editor.passTimeout": "No se confirmó: Pase. Se conserva tu borrador; puedes reintentarlo.",
  "editor.passFailed": "No se pudo enviar: Pase. Se conserva tu borrador.",
  "editor.passPending": "Esperando confirmación: Pase…",
  "editor.exchangeTimeout": "No se confirmó: Cambio. Se conserva tu borrador; puedes reintentarlo.",
  "editor.exchangeFailed": "No se pudo enviar: Cambio. Se conserva tu borrador.",
  "editor.exchangePending": "Esperando confirmación: Cambio…",
};
export const catalogs = { en, de, es };
export type Locale = keyof typeof catalogs;
export type Values = Record<string, string | number | bigint>;
export type Copy = { key: CopyKey; values?: Values };
export function copy(key: CopyKey, values?: Values): Copy {
  return { key, ...(values === undefined ? {} : { values }) };
}
const numberFormats = {
  en: new Intl.NumberFormat("en"),
  de: new Intl.NumberFormat("de"),
  es: new Intl.NumberFormat("es"),
};
const signedFormats = {
  en: new Intl.NumberFormat("en", { signDisplay: "exceptZero" }),
  de: new Intl.NumberFormat("de", { signDisplay: "exceptZero" }),
  es: new Intl.NumberFormat("es", { signDisplay: "exceptZero" }),
};
export function formatNumber(locale: Locale, value: number | bigint, signed = false): string {
  return (signed ? signedFormats : numberFormats)[locale].format(value);
}
export function translate(locale: Locale, message: Copy | CopyKey, values?: Values): string {
  const key = typeof message === "string" ? message : message.key;
  const parameters = typeof message === "string" ? values : message.values;
  return catalogs[locale][key].replace(/\{([a-zA-Z]+)\}/g, (_, name: string) => {
    const value = parameters?.[name];
    if (value === undefined) {
      throw new Error(`Missing copy parameter: ${key}.${name}`);
    }
    return typeof value === "string" ? value : formatNumber(locale, value);
  });
}
